export const stats = [
  {
    title: "My Active Leads",
    value: "47",
    note: "12 new this week",
    tone: "primary",
  },
  {
    title: "Converted",
    value: "18",
    note: "38% conversion rate",
    tone: "success",
  },
  {
    title: "Overdue Follow-ups",
    value: "7",
    note: "Needs attention",
    tone: "warning",
  },
  { title: "Lost", value: "5", note: "3 this month", tone: "danger" },
];

export const followUps = [
  {
    name: "Rohit Sharma",
    detail: "Grade 5 · Phone Call",
    time: "10:30 AM",
    status: "Overdue",
  },
  {
    name: "Ananya Gupta",
    detail: "Grade 3 · School Visit",
    time: "11:45 AM",
    status: "Scheduled",
  },
  {
    name: "Vihaan Mehta",
    detail: "Nursery · WhatsApp",
    time: "01:00 PM",
    status: "Scheduled",
  },
  {
    name: "Saanvi Iyer",
    detail: "Grade 7 · Parent Call",
    time: "03:10 PM",
    status: "Overdue",
  },
  {
    name: "Kabir Singh",
    detail: "Grade 1 · Document Check",
    time: "04:00 PM",
    status: "Scheduled",
  },
];

export const activities = [
  "You marked Ananya Gupta as Visit Completed",
  "Fee details shared with Rohit Sharma's parent",
  "Added a new lead: Kavya Verma (Grade 2)",
  "Moved Vihaan Mehta to Application Submitted",
  "Set callback reminder for Saanvi Iyer",
  "Updated notes for Kabir Singh lead",
];

export const pipelineColumns = [
  {
    key: "new",
    label: "New",
    count: 12,
    color: "#2563EB",
    cards: [
      {
        name: "Arjun Patel",
        grade: "Grade 3",
        source: "Walk-in",
        sourceTone: "source-amber",
        date: "13 Apr",
        overdue: true,
      },
      {
        name: "Aditi Sharma",
        grade: "Grade 1",
        source: "Website",
        sourceTone: "source-blue",
        date: "12 Apr",
        overdue: false,
      },
      {
        name: "Yash Thakur",
        grade: "Nursery",
        source: "Reference",
        sourceTone: "source-violet",
        date: "11 Apr",
        overdue: false,
      },
    ],
  },
  {
    key: "contacted",
    label: "Contacted",
    count: 8,
    color: "#4F46E5",
    cards: [
      {
        name: "Meera Nair",
        grade: "Grade 4",
        source: "Instagram",
        sourceTone: "source-pink",
        date: "12 Apr",
        overdue: false,
      },
      {
        name: "Raghav Verma",
        grade: "Grade 2",
        source: "Facebook",
        sourceTone: "source-sky",
        date: "10 Apr",
        overdue: true,
      },
      {
        name: "Neha Jain",
        grade: "Grade 6",
        source: "Website",
        sourceTone: "source-blue",
        date: "09 Apr",
        overdue: false,
      },
    ],
  },
  {
    key: "nurturing",
    label: "Nurturing",
    count: 15,
    color: "#0D9488",
    cards: [
      {
        name: "Ishaan Khan",
        grade: "Grade 5",
        source: "Walk-in",
        sourceTone: "source-amber",
        date: "14 Apr",
        overdue: false,
      },
      {
        name: "Sneha Gupta",
        grade: "Grade 8",
        source: "Google Ads",
        sourceTone: "source-cyan",
        date: "13 Apr",
        overdue: false,
      },
      {
        name: "Ritu Solanki",
        grade: "Grade 2",
        source: "Reference",
        sourceTone: "source-violet",
        date: "08 Apr",
        overdue: true,
      },
    ],
  },
  {
    key: "visit-scheduled",
    label: "Visit Scheduled",
    count: 6,
    color: "#F59E0B",
    cards: [
      {
        name: "Aman Dubey",
        grade: "Grade 7",
        source: "Website",
        sourceTone: "source-blue",
        date: "15 Apr",
        overdue: false,
        backdated: true,
      },
      {
        name: "Pooja Rawat",
        grade: "Grade 3",
        source: "Walk-in",
        sourceTone: "source-amber",
        date: "14 Apr",
        overdue: false,
      },
      {
        name: "Kunal Bansal",
        grade: "Grade 1",
        source: "Instagram",
        sourceTone: "source-pink",
        date: "11 Apr",
        overdue: true,
      },
    ],
  },
  {
    key: "visit-completed",
    label: "Visit Completed",
    count: 4,
    color: "#EA580C",
    cards: [
      {
        name: "Lakshmi Menon",
        grade: "Grade 5",
        source: "Reference",
        sourceTone: "source-violet",
        date: "09 Apr",
        overdue: false,
      },
      {
        name: "Omkar Joshi",
        grade: "Grade 4",
        source: "Website",
        sourceTone: "source-blue",
        date: "08 Apr",
        overdue: false,
      },
    ],
  },
  {
    key: "form-issued",
    label: "Form Issued",
    count: 3,
    color: "#7C3AED",
    cards: [
      {
        name: "Bhavya Singh",
        grade: "Grade 6",
        source: "Facebook",
        sourceTone: "source-sky",
        date: "10 Apr",
        overdue: false,
      },
      {
        name: "Tanya Kapoor",
        grade: "Grade 2",
        source: "Walk-in",
        sourceTone: "source-amber",
        date: "09 Apr",
        overdue: false,
      },
    ],
  },
  {
    key: "converted",
    label: "Converted ✅",
    count: 18,
    color: "#16A34A",
    cards: [
      {
        name: "Dev Mishra",
        grade: "Grade 3",
        source: "Website",
        sourceTone: "source-blue",
        date: "07 Apr",
        overdue: false,
      },
      {
        name: "Sia Tiwari",
        grade: "Grade 1",
        source: "Reference",
        sourceTone: "source-violet",
        date: "06 Apr",
        overdue: false,
      },
      {
        name: "Nitin Yadav",
        grade: "Nursery",
        source: "Walk-in",
        sourceTone: "source-amber",
        date: "05 Apr",
        overdue: false,
      },
    ],
  },
];

export const tableRows = [
  /*
  {
    selected: false,
    leadId: "LM-0247",
    student: "Aarav Mehta",
    parent: "Sunita Mehta",
    contact: "+91 98765 43210",
    grade: "Grade 5",
    source: "Website",
    sourceTone: "source-blue",
    status: "Nurturing",
    statusTone: "status-teal",
    enquiry: "08 Apr 2026",
    followUp: "11 Apr - Phone",
    nextAction: "14 Apr",
    overdue: false,
  },
  {
    selected: true,
    leadId: "LM-0248",
    student: "Diya Malhotra",
    parent: "Renu Malhotra",
    contact: "+91 99887 66554",
    grade: "Grade 2",
    source: "Walk-in",
    sourceTone: "source-amber",
    status: "Contacted",
    statusTone: "status-indigo",
    enquiry: "06 Apr 2026",
    followUp: "10 Apr - Visit",
    nextAction: "12 Apr",
    overdue: true,
  },
  {
    selected: false,
    leadId: "LM-0249",
    student: "Reyansh Chauhan",
    parent: "Pankaj Chauhan",
    contact: "+91 98712 33445",
    grade: "Nursery",
    source: "Instagram",
    sourceTone: "source-pink",
    status: "New",
    statusTone: "status-blue",
    enquiry: "09 Apr 2026",
    followUp: "11 Apr - WhatsApp",
    nextAction: "14 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0250",
    student: "Myra Arora",
    parent: "Alok Arora",
    contact: "+91 98111 22334",
    grade: "Grade 4",
    source: "Facebook",
    sourceTone: "source-sky",
    status: "Nurturing",
    statusTone: "status-teal",
    enquiry: "05 Apr 2026",
    followUp: "11 Apr - Phone",
    nextAction: "15 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0251",
    student: "Krishna Jha",
    parent: "Neetu Jha",
    contact: "+91 98900 77881",
    grade: "Grade 3",
    source: "Reference",
    sourceTone: "source-violet",
    status: "Visit Scheduled",
    statusTone: "status-amber",
    enquiry: "03 Apr 2026",
    followUp: "12 Apr - Visit",
    nextAction: "16 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0252",
    student: "Anvi Sood",
    parent: "Deepa Sood",
    contact: "+91 99001 11223",
    grade: "Grade 6",
    source: "Google Ads",
    sourceTone: "source-cyan",
    status: "Contacted",
    statusTone: "status-indigo",
    enquiry: "02 Apr 2026",
    followUp: "10 Apr - Phone",
    nextAction: "13 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0253",
    student: "Harshita Rao",
    parent: "Girish Rao",
    contact: "+91 99777 66552",
    grade: "Grade 7",
    source: "Website",
    sourceTone: "source-blue",
    status: "Visit Completed",
    statusTone: "status-orange",
    enquiry: "01 Apr 2026",
    followUp: "09 Apr - Visit",
    nextAction: "17 Apr",
    overdue: false,
  },
  {
    selected: true,
    leadId: "LM-0254",
    student: "Kabir Anand",
    parent: "Manju Anand",
    contact: "+91 99100 44556",
    grade: "Grade 1",
    source: "Walk-in",
    sourceTone: "source-amber",
    status: "Form Issued",
    statusTone: "status-violet",
    enquiry: "04 Apr 2026",
    followUp: "11 Apr - Docs",
    nextAction: "12 Apr",
    overdue: true,
  },
  {
    selected: false,
    leadId: "LM-0255",
    student: "Riya Bhardwaj",
    parent: "Sanjay Bhardwaj",
    contact: "+91 98888 77665",
    grade: "Grade 8",
    source: "Instagram",
    sourceTone: "source-pink",
    status: "Nurturing",
    statusTone: "status-teal",
    enquiry: "07 Apr 2026",
    followUp: "12 Apr - Phone",
    nextAction: "18 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0256",
    student: "Shivam Rana",
    parent: "Kiran Rana",
    contact: "+91 98123 45678",
    grade: "Grade 4",
    source: "Reference",
    sourceTone: "source-violet",
    status: "Converted",
    statusTone: "status-green",
    enquiry: "28 Mar 2026",
    followUp: "08 Apr - Fee",
    nextAction: "Completed",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0257",
    student: "Samar Gill",
    parent: "Anita Gill",
    contact: "+91 98989 11221",
    grade: "Grade 2",
    source: "Website",
    sourceTone: "source-blue",
    status: "New",
    statusTone: "status-blue",
    enquiry: "10 Apr 2026",
    followUp: "12 Apr - Intro",
    nextAction: "14 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0258",
    student: "Naina Kaul",
    parent: "Rohit Kaul",
    contact: "+91 99220 77441",
    grade: "Grade 5",
    source: "Facebook",
    sourceTone: "source-sky",
    status: "Contacted",
    statusTone: "status-indigo",
    enquiry: "06 Apr 2026",
    followUp: "11 Apr - Phone",
    nextAction: "15 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0259",
    student: "Vedika Dutt",
    parent: "Pooja Dutt",
    contact: "+91 98700 22134",
    grade: "Grade 3",
    source: "Google Ads",
    sourceTone: "source-cyan",
    status: "Visit Scheduled",
    statusTone: "status-amber",
    enquiry: "05 Apr 2026",
    followUp: "12 Apr - Call",
    nextAction: "16 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0260",
    student: "Parth Sinha",
    parent: "Neha Sinha",
    contact: "+91 99712 66743",
    grade: "Nursery",
    source: "Walk-in",
    sourceTone: "source-amber",
    status: "Nurturing",
    statusTone: "status-teal",
    enquiry: "09 Apr 2026",
    followUp: "12 Apr - Home Visit",
    nextAction: "17 Apr",
    overdue: false,
  },
  {
    selected: false,
    leadId: "LM-0261",
    student: "Jhanvi Chawla",
    parent: "Rakesh Chawla",
    contact: "+91 98654 44112",
    grade: "Grade 6",
    source: "Website",
    sourceTone: "source-blue",
    status: "Visit Completed",
    statusTone: "status-orange",
    enquiry: "04 Apr 2026",
    followUp: "10 Apr - Visit",
    nextAction: "18 Apr",
    overdue: false,
  },
  ...Array.from({ length: 30 }, (_, index) => {
    const rowNumber = index + 1;
    const statusOptions = [
      { status: "New", statusTone: "status-blue" },
      { status: "Contacted", statusTone: "status-indigo" },
      { status: "Nurturing", statusTone: "status-teal" },
      { status: "Visit Scheduled", statusTone: "status-amber" },
      { status: "Visit Completed", statusTone: "status-orange" },
      { status: "Form Issued", statusTone: "status-violet" },
      { status: "Converted", statusTone: "status-green" },
    ];
    const sourceOptions = [
      { source: "Website", sourceTone: "source-blue" },
      { source: "Walk-in", sourceTone: "source-amber" },
      { source: "Instagram", sourceTone: "source-pink" },
      { source: "Facebook", sourceTone: "source-sky" },
      { source: "Reference", sourceTone: "source-violet" },
      { source: "Google Ads", sourceTone: "source-cyan" },
    ];
    const grades = [
      "Nursery",
      "LKG",
      "UKG",
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
      "Grade 10",
      "Grade 11",
      "Grade 12",
    ];
    const status = statusOptions[index % statusOptions.length];
    const source = sourceOptions[index % sourceOptions.length];
    const enquiryDay = String((index % 28) + 1).padStart(2, "0");
    const followUpDay = String(((index + 3) % 28) + 1).padStart(2, "0");
    const nextActionDay = String(((index + 5) % 28) + 1).padStart(2, "0");

    return {
      selected: index % 5 === 0,
      leadId: `LM-${String(262 + index).padStart(4, "0")}`,
      student: `Demo Student ${rowNumber}`,
      parent: `Demo Parent ${rowNumber}`,
      contact: `+91 99000 3${String(rowNumber).padStart(2, "0")}`,
      grade: grades[index % grades.length],
      source: source.source,
      sourceTone: source.sourceTone,
      status: status.status,
      statusTone: status.statusTone,
      enquiry: `${enquiryDay} Apr 2026`,
      followUp: `${followUpDay} Apr - Call`,
      nextAction: `${nextActionDay} Apr`,
      overdue: index % 4 === 0,
    };
  }),
  */
];

export const leadTimeline = [
  {
    type: "Phone Call",
    date: "11 Apr 2026 · 2:30 PM · Phone Call",
    note: "Spoke with father. Interested in visiting campus next week. Will call back on Monday to confirm date.",
    author: "Arunav Kishor",
    tone: "blue",
    icon: "phone",
  },
  {
    type: "WhatsApp",
    date: "09 Apr 2026 · 11:00 AM · WhatsApp",
    note: "Sent school brochure and fee structure PDF. Parent acknowledged receipt.",
    author: "Arunav Kishor",
    tone: "green",
    icon: "chat",
  },
  {
    type: "Phone Call",
    date: "08 Apr 2026 · 3:15 PM · Phone Call",
    note: "First contact. Parent enquired about Grade 5 admission. Interested in CBSE curriculum and sports facilities.",
    author: "Arunav Kishor",
    tone: "blue",
    icon: "phone",
  },
  {
    type: "System",
    date: "08 Apr 2026 · 10:00 AM · System",
    note: "Lead created from website form. Auto-assigned to Arunav Kishor.",
    author: "System",
    tone: "purple",
    icon: "sparkle",
    system: true,
  },
];

export const leadActions = [
  { key: "followup", label: "Follow-up", tone: "action-blue", icon: "phone" },
  {
    key: "schedule",
    label: "Schedule Visit",
    tone: "action-amber",
    icon: "calendar",
  },
  { key: "issue", label: "Issue Form", tone: "action-violet", icon: "file" },
  {
    key: "convert",
    label: "Mark Converted",
    tone: "action-green",
    icon: "check",
  },
  { key: "lost", label: "Mark Lost", tone: "action-red", icon: "x" },
  { key: "edit", label: "Edit Lead", tone: "action-gray", icon: "edit" },
];

export const modalModes = [
  { label: "Call", icon: "phone", active: true },
  { label: "Visit", icon: "calendar" },
  { label: "WhatsApp", icon: "chat" },
  { label: "SMS", icon: "mail" },
  { label: "Other", icon: "clipboard" },
];

export const notifications = [
  {
    text: "Overdue: Follow-up with Ananya Gupta (Grade 8) was due 2 days ago.",
    time: "2 hours ago",
    unread: true,
    tone: "red",
  },
  {
    text: "New lead assigned: Vikram Singh, Grade 3, Walk-in. Contact within 24 hours.",
    time: "3 hours ago",
    unread: true,
    tone: "blue",
  },
  {
    text: "Reminder: Campus visit for Rohit Sharma tomorrow at 10 AM.",
    time: "5 hours ago",
    unread: true,
    tone: "amber",
  },
  {
    text: "Lead LM-0232 marked as Converted by you. Great work!",
    time: "Yesterday",
    unread: false,
    tone: "green",
  },
  {
    text: "SLA Alert: 3 leads have had no activity for 5+ days. Please follow up.",
    time: "Yesterday",
    unread: false,
    tone: "red",
  },
  {
    text: "New lead from Instagram campaign 'Summer 2026' - auto-assigned to you.",
    time: "2 days ago",
    unread: false,
    tone: "pink",
  },
];
